"""
PostgreSQL moslashtiruvchi qatlam (shim) — Faza 0.

Maqsad: `database.py` dagi ~89 ta sqlite3 so'rovini O'ZGARTIRMASDAN PostgreSQL'da
ishlatish. Shim sqlite3.Connection/Cursor API'sini taqlid qiladi, lekin ostida
psycopg (PostgreSQL) bilan gaplashadi.

Asosiy ish:
  - `?`            -> `%s`                (placeholder)
  - `CURRENT_TIMESTAMP` -> to_char(now()...)  (TEXT-timestamp parity, 'YYYY-MM-DD HH:MM:SS')
  - `INSERT OR IGNORE` -> `INSERT ... ON CONFLICT DO NOTHING`
  - `INSERT OR REPLACE` -> `INSERT ... ON CONFLICT DO NOTHING`  (best-effort; kodda hozir ishlatilmaydi)
  - `cursor.lastrowid` -> INSERT'ga `RETURNING id` qo'shib ushlaymiz (app_meta uchun fallback)
  - DDL: `INTEGER PRIMARY KEY AUTOINCREMENT` -> IDENTITY; INTEGER->BIGINT, REAL->DOUBLE
    PRECISION, BOOLEAN->SMALLINT, TIMESTAMP->TEXT
  - `strftime('%H'/'%w', x)` -> EXTRACT(HOUR/DOW ...)   (analitika)
  - `PRAGMA ...` -> no-op
  - Natija qatorlari sqlite3.Row kabi: row[0] HAM row['col'] HAM dict(row) ishlaydi.

MUHIM (tranzaksiya): har bir execute SAVEPOINT ichida bajariladi — ushlangan xato
(try/except) butun tranzaksiyani buzmasin (SQLite "forgiveness" emulatsiyasi). Bu
`init_db` dagi try/except ALTER naqshi uchun zarur.

Bu modul faqat DB_BACKEND=postgres bo'lganda import qilinadi.
"""
import re
import logging

# TIMESTAMP ustunlari uchun: SQLite CURRENT_TIMESTAMP -> 'YYYY-MM-DD HH:MM:SS' (UTC).
# PG'da aynan shu formatni beradigan ifoda (parity uchun TEXT ustunga yoziladi):
PG_NOW_TEXT = "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')"


# ============================================================
# SQL TARJIMA (sof funksiya — PG'siz test qilinadi)
# ============================================================
def _split_literals(sql: str):
    """SQL'ni ['string-literal' | oddiy-matn] bo'laklarga ajratadi.
    Qaytaradi: [(is_string, text), ...]. '' (qo'sh apostrof) escape hisobga olinadi."""
    out, buf, i, n = [], [], 0, len(sql)
    while i < n:
        ch = sql[i]
        if ch == "'":
            if buf:
                out.append((False, "".join(buf)))
                buf = []
            s = ["'"]
            i += 1
            while i < n:
                if sql[i] == "'":
                    if i + 1 < n and sql[i + 1] == "'":
                        s.append("''")
                        i += 2
                        continue
                    s.append("'")
                    i += 1
                    break
                s.append(sql[i])
                i += 1
            out.append((True, "".join(s)))
        else:
            buf.append(ch)
            i += 1
    if buf:
        out.append((False, "".join(buf)))
    return out


def _apply_outside_strings(sql: str, fn) -> str:
    """fn ni faqat string-literal bo'lmagan bo'laklarga qo'llaydi."""
    return "".join(seg if is_str else fn(seg) for is_str, seg in _split_literals(sql))


# DDL tip almashtirishlari (faqat CREATE/ALTER uchun, katta harfli tip so'zlari)
_DDL_TYPE_SUBS = [
    (re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.I),
     "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (re.compile(r"\bAUTOINCREMENT\b", re.I), ""),
    (re.compile(r"\bINTEGER\b", re.I), "BIGINT"),
    (re.compile(r"\bREAL\b", re.I), "DOUBLE PRECISION"),
    (re.compile(r"\bBOOLEAN\b", re.I), "SMALLINT"),
    (re.compile(r"\bTIMESTAMP\b", re.I), "TEXT"),
]

_RE_STRFTIME_H = re.compile(r"strftime\(\s*'%H'\s*,\s*([^)]+?)\s*\)", re.I)
_RE_STRFTIME_W = re.compile(r"strftime\(\s*'%w'\s*,\s*([^)]+?)\s*\)", re.I)
# SQLite datetime('now', '-7 days') -> PG to_char(now()...-interval, 'YYYY-MM-DD HH24:MI:SS')
# (created_at TEXT bilan string-solishtirish uchun aynan shu format).
_RE_DATETIME_NOW = re.compile(
    r"datetime\(\s*'now'\s*(?:,\s*'\s*([+-]?)\s*(\d+)\s+(\w+)\s*'\s*)?\)", re.I
)


def _datetime_now_repl(m):
    sign, num, unit = m.group(1), m.group(2), m.group(3)
    if num is None:
        expr = "(now() AT TIME ZONE 'UTC')"
    else:
        op = "-" if sign == "-" else "+"
        expr = f"(now() AT TIME ZONE 'UTC' {op} interval '{num} {unit}')"
    return f"to_char({expr}, 'YYYY-MM-DD HH24:MI:SS')"
_RE_CURRENT_TS = re.compile(r"\bCURRENT_TIMESTAMP\b", re.I)
_RE_INSERT_IGNORE = re.compile(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", re.I)
_RE_INSERT_REPLACE = re.compile(r"^\s*INSERT\s+OR\s+REPLACE\s+INTO\b", re.I)
_RE_IS_INSERT = re.compile(r"^\s*INSERT\s+INTO\b", re.I)
_RE_IS_DDL = re.compile(r"^\s*(CREATE|ALTER|DROP)\b", re.I)


def translate_sql(sql: str) -> str:
    """sqlite3 so'rovini PostgreSQL so'roviga aylantiradi. Sof string->string."""
    # 1) strftime (SQL ichidagi literal % ni ham olib tashlaydi)
    sql = _RE_STRFTIME_H.sub(r"CAST(EXTRACT(HOUR FROM (\1)::timestamp) AS INTEGER)", sql)
    sql = _RE_STRFTIME_W.sub(r"CAST(EXTRACT(DOW FROM (\1)::timestamp) AS INTEGER)", sql)
    # 1b) datetime('now', '-N days')
    sql = _RE_DATETIME_NOW.sub(_datetime_now_repl, sql)

    # 2) DDL tip almashtirishlari
    if _RE_IS_DDL.match(sql):
        for rx, repl in _DDL_TYPE_SUBS:
            sql = rx.sub(repl, sql)

    # 3) CURRENT_TIMESTAMP -> to_char(...)  (string literal ichida emas)
    sql = _apply_outside_strings(sql, lambda s: _RE_CURRENT_TS.sub(PG_NOW_TEXT, s))

    # 4) INSERT OR IGNORE / REPLACE
    on_conflict = False
    if _RE_INSERT_IGNORE.match(sql):
        sql = _RE_INSERT_IGNORE.sub(lambda m: m.group(0).replace("OR IGNORE", "").replace("or ignore", ""), sql, count=1)
        sql = re.sub(r"^\s*INSERT\s+INTO\b", "INSERT INTO", sql, count=1, flags=re.I)
        on_conflict = True
    elif _RE_INSERT_REPLACE.match(sql):
        # Best-effort: konflikt ustunlarini bilmaganimiz uchun DO NOTHING.
        sql = re.sub(r"^\s*INSERT\s+OR\s+REPLACE\s+INTO\b", "INSERT INTO", sql, count=1, flags=re.I)
        on_conflict = True

    # 5) literal % -> %% (psycopg talabi). %s hali yo'q, shuning uchun xavfsiz.
    sql = sql.replace("%", "%%")

    # 6) ? -> %s  (string literal ichida emas)
    sql = _apply_outside_strings(sql, lambda s: s.replace("?", "%s"))

    if on_conflict:
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return sql


# ============================================================
# ROW — sqlite3.Row taqlidi (int index VA kalit bo'yicha)
# ============================================================
class _Row:
    __slots__ = ("_vals", "_cols")

    def __init__(self, vals, cols):
        self._vals = vals
        self._cols = cols  # {colname: index}

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._vals[key]
        if isinstance(key, slice):
            return self._vals[key]
        return self._vals[self._cols[key]]

    def __iter__(self):
        return iter(self._vals)

    def __len__(self):
        return len(self._vals)

    def keys(self):
        return list(self._cols.keys())

    def __contains__(self, key):
        return key in self._cols

    def get(self, key, default=None):
        idx = self._cols.get(key)
        return self._vals[idx] if idx is not None else default


# ============================================================
# CURSOR
# ============================================================
class PgCursor:
    def __init__(self, conn):
        self._conn = conn
        self._cur = conn._pg.cursor()
        self._buf = []
        self._idx = 0
        self._cols_map = {}   # ustun-nomlari -> index (RELEASE'dan oldin saqlanadi)
        self.lastrowid = None
        self.rowcount = -1

    def _cols(self):
        # RELEASE/commit'dan keyin self._cur.description None bo'ladi — shuning uchun
        # execute paytida saqlangan ustun xaritasini qaytaramiz (audit #1 fix).
        return self._cols_map

    def execute(self, sql, params=None):
        params = tuple(params) if params else ()

        # PRAGMA -> no-op
        if re.match(r"^\s*PRAGMA\b", sql, re.I):
            self._buf, self._idx, self.lastrowid, self.rowcount = [], 0, None, -1
            self._cols_map = {}
            return self

        translated = translate_sql(sql)
        is_insert = bool(_RE_IS_INSERT.match(translated))
        has_returning = " RETURNING " in (" " + translated.upper() + " ")
        is_ddl = bool(_RE_IS_DDL.match(translated))

        sp = self._conn._next_savepoint()
        self._cur.execute(f"SAVEPOINT {sp}")
        try:
            if is_insert and not has_returning:
                # lastrowid uchun RETURNING id — id ustuni bo'lmasa fallback
                try:
                    self._cur.execute(translated + " RETURNING id", params)
                except Exception:
                    self._cur.execute(f"ROLLBACK TO SAVEPOINT {sp}")
                    self._cur.execute(translated, params)
            else:
                self._cur.execute(translated, params)
            # MUHIM (audit #1 fix): natija + ustun-nomlarni RELEASE'dan OLDIN o'qiymiz.
            # RELEASE SAVEPOINT o'sha cursor'da bajarilsa, psycopg cursor.description'ni
            # None qiladi va natija to'plami yo'qoladi — shu sabab BARCHA SELECT bo'sh
            # qaytar edi. Buferlash endi RELEASE'dan oldin.
            self.rowcount = self._cur.rowcount
            if self._cur.description is not None:
                self._cols_map = {d.name: i for i, d in enumerate(self._cur.description)}
                captured = self._cur.fetchall()
            else:
                self._cols_map = {}
                captured = []
            self._cur.execute(f"RELEASE SAVEPOINT {sp}")
        except Exception:
            try:
                self._cur.execute(f"ROLLBACK TO SAVEPOINT {sp}")
                self._cur.execute(f"RELEASE SAVEPOINT {sp}")
            except Exception:
                pass
            raise

        self._idx = 0
        if is_insert and not has_returning:
            # RETURNING id natijasi -> lastrowid
            self.lastrowid = captured[0][0] if captured else None
            self._buf = []
        else:
            self._buf = captured

        if is_insert or is_ddl or re.match(r"^\s*(UPDATE|DELETE)\b", translated, re.I):
            self._conn._dirty = True
        else:
            # faqat o'qish bo'lsa va yozilmagan o'zgarish yo'q bo'lsa — snapshotni bo'shatamiz
            self._conn._maybe_autocommit_read()
        return self

    def executemany(self, sql, seq_of_params):
        translated = translate_sql(sql)
        sp = self._conn._next_savepoint()
        self._cur.execute(f"SAVEPOINT {sp}")
        try:
            self._cur.executemany(translated, [tuple(p) for p in seq_of_params])
            self._cur.execute(f"RELEASE SAVEPOINT {sp}")
        except Exception:
            try:
                self._cur.execute(f"ROLLBACK TO SAVEPOINT {sp}")
                self._cur.execute(f"RELEASE SAVEPOINT {sp}")
            except Exception:
                pass
            raise
        self.rowcount = self._cur.rowcount
        self.lastrowid = None
        self._buf, self._idx, self._cols_map = [], 0, {}
        self._conn._dirty = True
        return self

    def _wrap(self, row):
        if row is None:
            return None
        return _Row(list(row), self._cols())

    def fetchone(self):
        if self._idx >= len(self._buf):
            return None
        row = self._buf[self._idx]
        self._idx += 1
        return self._wrap(row)

    def fetchall(self):
        rows = self._buf[self._idx:]
        self._idx = len(self._buf)
        cols = self._cols()
        return [_Row(list(r), cols) for r in rows]

    def fetchmany(self, size=1):
        rows = self._buf[self._idx:self._idx + size]
        self._idx += len(rows)
        cols = self._cols()
        return [_Row(list(r), cols) for r in rows]

    def __iter__(self):
        return iter(self.fetchall())

    def close(self):
        try:
            self._cur.close()
        except Exception:
            pass


# ============================================================
# CONNECTION
# ============================================================
class PgConnection:
    def __init__(self, pg_conn):
        self._pg = pg_conn
        self._pg.autocommit = False
        self._dirty = False
        self._sp_counter = 0
        self.row_factory = None  # sqlite3.Row uchun no-op (shim o'zi _Row qaytaradi)

    def _next_savepoint(self):
        self._sp_counter += 1
        return f"_sp{self._sp_counter}"

    def _maybe_autocommit_read(self):
        """Faqat o'qishdan keyin, yozilmagan o'zgarish yo'q bo'lsa — tranzaksiyani
        yopamiz (idle-in-transaction va eskirgan snapshotning oldini olish)."""
        if not self._dirty:
            try:
                self._pg.commit()
            except Exception:
                pass

    def cursor(self):
        return PgCursor(self)

    def execute(self, sql, params=None):
        cur = self.cursor()
        cur.execute(sql, params)
        return cur

    def commit(self):
        self._pg.commit()
        self._dirty = False

    def rollback(self):
        self._pg.rollback()
        self._dirty = False

    def close(self):
        try:
            self._pg.close()
        except Exception:
            pass


def connect(dsn: str) -> PgConnection:
    import psycopg
    return PgConnection(psycopg.connect(dsn))
