"""
SQLite -> PostgreSQL ko'chirish vositasi (Faza 0).

Maqsad: marketplace.db (SQLite) ni PostgreSQL'ga 100% 1:1 ko'chirish.
Kalit g'oya — TIP PARISITETI: schema shunday generatsiya qilinadiki, psycopg
AYNAN o'sha Python tiplarini qaytarsin (str/int/float) — shunda main.py va
boshqa biznes-mantiqqa tegmasdan ishlaydi.

    SQLite tip       -> PostgreSQL tip      -> Python (psycopg)
    INTEGER (pk)     -> BIGINT IDENTITY      -> int
    INTEGER          -> BIGINT               -> int   (telegram_id 2^31 dan oshadi!)
    REAL             -> DOUBLE PRECISION      -> float
    BOOLEAN          -> SMALLINT              -> int   (0/1 — kod shunday kutadi)
    TIMESTAMP        -> TEXT                  -> str   ('YYYY-MM-DD HH:MM:SS')
    TEXT             -> TEXT                  -> str

Ishlatish:
    # Faqat DDL ni ko'rish (PG kerak emas):
    python pg_migrate.py --dry-run

    # Haqiqiy ko'chirish (PG kerak):
    python pg_migrate.py --pg-dsn "postgresql://user:pass@host:5432/dbname"

    # Faqat schema (ma'lumotsiz):
    python pg_migrate.py --pg-dsn "..." --schema-only
"""
import sqlite3
import argparse
import sys

DEFAULT_SQLITE = "marketplace.db"

# ===== TIP PARISITETI =====
# SQLite e'lon qilingan tip (katta harf) -> PostgreSQL tip.
# IDENTITY (autoincrement pk) alohida hal qilinadi.
TYPE_MAP = {
    "INTEGER": "BIGINT",
    "REAL": "DOUBLE PRECISION",
    "BOOLEAN": "SMALLINT",      # parity: kod 0/1 (int) kutadi, True/False emas
    "TIMESTAMP": "TEXT",        # parity: 'YYYY-MM-DD HH:MM:SS' string saqlanadi
    "TEXT": "TEXT",
    "": "TEXT",                 # tipsiz ustun -> TEXT
}

# TIMESTAMP ustunlar uchun CURRENT_TIMESTAMP default'i — SQLite 'YYYY-MM-DD HH:MM:SS'
# (UTC) beradi. PG'da AYNAN shu formatni beradigan ifoda:
PG_NOW_TEXT = "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')"


def map_type(sqlite_type: str) -> str:
    """SQLite e'lon tipini PG tipiga aylantiradi."""
    return TYPE_MAP.get((sqlite_type or "").upper().strip(), "TEXT")


def list_tables(cur) -> list:
    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    return [r[0] for r in cur.fetchall()]


def table_columns(cur, table: str) -> list:
    """[(name, sqlite_type, notnull, default, is_pk), ...]"""
    cur.execute(f"PRAGMA table_info({table})")
    out = []
    for cid, name, typ, notnull, dflt, pk in cur.fetchall():
        out.append((name, typ, bool(notnull), dflt, bool(pk)))
    return out


def table_uniques(cur, table: str) -> list:
    """origin='u' UNIQUE cheklovlari: [[col, ...], ...]  (pk va explicit indekslar emas)."""
    out = []
    for idx in cur.execute(f"PRAGMA index_list({table})").fetchall():
        # (seq, name, unique, origin, partial)
        _seq, name, unique, origin, _partial = idx
        if unique == 1 and origin == "u":
            cols = [r[2] for r in cur.execute(f"PRAGMA index_info({name})").fetchall()]
            out.append(cols)
    return out


def table_fks(cur, table: str) -> list:
    """[(from_col, ref_table, ref_col, on_delete), ...]"""
    out = []
    for fk in cur.execute(f"PRAGMA foreign_key_list({table})").fetchall():
        # (id, seq, table, from, to, on_update, on_delete, match)
        out.append((fk[3], fk[2], fk[4], (fk[6] or "NO ACTION")))
    return out


def explicit_indexes(cur) -> list:
    """Foydalanuvchi yaratgan (avtomatik emas) indekslar — sqlite_master'dagi sql."""
    cur.execute(
        "SELECT name, tbl_name, sql FROM sqlite_master "
        "WHERE type='index' AND sql IS NOT NULL ORDER BY tbl_name"
    )
    return cur.fetchall()


def build_column_ddl(name, sqlite_type, notnull, default, is_pk) -> str:
    """Bitta ustun uchun PG DDL bo'lagi."""
    pg_type = map_type(sqlite_type)

    # Autoincrement birlamchi kalit (INTEGER pk) -> IDENTITY (default'siz)
    if is_pk and (sqlite_type or "").upper().strip() == "INTEGER":
        return f"{name} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

    parts = [name, pg_type]

    # DEFAULT
    if default is not None:
        d = str(default).strip()
        if d.upper() == "CURRENT_TIMESTAMP":
            parts.append(f"DEFAULT {PG_NOW_TEXT}")
        else:
            # son yoki 'string' — SQLite saqlagan ko'rinishda (qo'shtirnoq bilan) uzatamiz
            parts.append(f"DEFAULT {d}")

    # INTEGER bo'lmagan birlamchi kalit (masalan app_meta.key TEXT PRIMARY KEY)
    if is_pk:
        parts.append("PRIMARY KEY")
    elif notnull:
        parts.append("NOT NULL")

    return " ".join(parts)


def generate_ddl(cur):
    """Jonli SQLite'dan to'liq PG DDL generatsiya qiladi.
    Qaytaradi: (create_statements, index_statements, fk_statements, tables)"""
    tables = list_tables(cur)
    creates, indexes, fks = [], [], []

    for t in tables:
        cols = table_columns(cur, t)
        uniques = table_uniques(cur, t)

        lines = [build_column_ddl(*c) for c in cols]
        for ucols in uniques:
            lines.append(f"UNIQUE ({', '.join(ucols)})")

        body = ",\n    ".join(lines)
        creates.append(f"CREATE TABLE IF NOT EXISTS {t} (\n    {body}\n);")

        # FK'lar — ma'lumot yuklangandan KEYIN qo'shiladi (load tartibi muhim emas)
        for from_col, ref_table, ref_col, on_delete in table_fks(cur, t):
            cascade = " ON DELETE CASCADE" if on_delete.upper() == "CASCADE" else ""
            cname = f"fk_{t}_{from_col}"
            fks.append(
                f"ALTER TABLE {t} ADD CONSTRAINT {cname} "
                f"FOREIGN KEY ({from_col}) REFERENCES {ref_table}({ref_col}){cascade};"
            )

    # Explicit indekslar (CREATE INDEX ... IF NOT EXISTS SQLite bilan mos)
    for name, tbl, sql in explicit_indexes(cur):
        s = sql.strip().rstrip(";")
        # SQLite "CREATE INDEX name ON ..." -> "IF NOT EXISTS" qo'shamiz
        s = s.replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ", 1)
        s = s.replace("CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ", 1)
        indexes.append(s + ";")

    return creates, indexes, fks, tables


def dump_ddl(cur):
    creates, indexes, fks, _tables = generate_ddl(cur)
    out = ["-- ===== JADVALLAR ====="]
    out += creates
    if indexes:
        out += ["", "-- ===== INDEKSLAR ====="] + indexes
    out += ["", "-- ===== FOREIGN KEY (ma'lumotdan KEYIN) ====="] + fks
    return "\n\n".join(out)


def copy_data(sconn, pgconn, tables):
    """SQLite'dan PG'ga barcha qatorlarni ko'chiradi. Qaytaradi: {table: (sqlite_n, pg_n)}"""
    scur = sconn.cursor()
    report = {}
    for t in tables:
        cols = [c[0] for c in table_columns(scur, t)]
        collist = ", ".join(cols)
        placeholders = ", ".join(["%s"] * len(cols))
        rows = scur.execute(f"SELECT {collist} FROM {t}").fetchall()
        pgcur = pgconn.cursor()
        if rows:
            pgcur.executemany(
                f"INSERT INTO {t} ({collist}) VALUES ({placeholders})",
                [tuple(r) for r in rows],
            )
        pgconn.commit()
        # tekshiruv
        pgcur.execute(f"SELECT COUNT(*) FROM {t}")
        pg_n = pgcur.fetchone()[0]
        report[t] = (len(rows), pg_n)
    return report


def reset_sequences(pgconn, tables):
    """IDENTITY ketma-ketliklarini max(id)+1 ga moslaydi (id ustuni bo'lsa)."""
    cur = pgconn.cursor()
    for t in tables:
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name=%s AND column_name='id'", (t,)
        )
        if not cur.fetchone():
            continue
        cur.execute(
            f"SELECT setval(pg_get_serial_sequence('{t}','id'), "
            f"COALESCE((SELECT MAX(id) FROM {t}), 1), "
            f"(SELECT COUNT(*) FROM {t}) > 0)"
        )
    pgconn.commit()


def main():
    ap = argparse.ArgumentParser(description="SQLite -> PostgreSQL ko'chirish")
    ap.add_argument("--sqlite", default=DEFAULT_SQLITE, help="SQLite fayl yo'li")
    ap.add_argument("--pg-dsn", help="PostgreSQL DSN (yo'q bo'lsa faqat DDL)")
    ap.add_argument("--dry-run", action="store_true", help="Faqat DDL ni chop etadi")
    ap.add_argument("--schema-only", action="store_true", help="Ma'lumotni ko'chirmaydi")
    args = ap.parse_args()

    sconn = sqlite3.connect(args.sqlite)
    scur = sconn.cursor()

    if args.dry_run or not args.pg_dsn:
        print(dump_ddl(scur))
        if not args.pg_dsn:
            print("\n-- (PG DSN berilmadi — faqat DDL ko'rsatildi)", file=sys.stderr)
        return

    try:
        import psycopg
    except ImportError:
        sys.exit("psycopg o'rnatilmagan:  pip install 'psycopg[binary]'")

    creates, indexes, fks, tables = generate_ddl(scur)
    pgconn = psycopg.connect(args.pg_dsn)

    print(">> Schema yaratilyapti...")
    with pgconn.cursor() as c:
        for stmt in creates + indexes:
            c.execute(stmt)
    pgconn.commit()

    if not args.schema_only:
        print(">> Ma'lumot ko'chirilyapti...")
        report = copy_data(sconn, pgconn, tables)
        print(">> Ketma-ketliklar (sequence) moslanyapti...")
        reset_sequences(pgconn, tables)
        print("\n=== TEKSHIRUV (SQLite -> PG qator soni) ===")
        ok = True
        for t, (sn, pn) in sorted(report.items()):
            flag = "OK" if sn == pn else "XATO!"
            if sn != pn:
                ok = False
            print(f"   {t:30s} {sn:>6} -> {pn:>6}  {flag}")
        print("=== " + ("HAMMASI MOS ✓" if ok else "MOS EMAS — TEKSHIRING!") + " ===")

    print(">> Foreign key cheklovlari qo'shilyapti...")
    with pgconn.cursor() as c:
        for stmt in fks:
            try:
                c.execute(stmt)
                pgconn.commit()
            except Exception as e:
                pgconn.rollback()
                print(f"   FK o'tkazib yuborildi: {e}")

    pgconn.close()
    print(">> Tugadi.")


if __name__ == "__main__":
    main()
