"""`db_backend.translate_sql` uchun karakterizatsiya (unit) testlari.

Bu testlar PostgreSQL'siz ishlaydi — sof string->string tarjimani qotiradi.
Maqsad: shim'ning SQLite->PG tarjima qoidalari kelajakdagi tahrirlarda jimgina
buzilmasin. Haqiqiy PG bilan round-trip esa `test_pg_shim_integration.py` da.
"""
import db_backend
from db_backend import translate_sql


# --- Placeholder: ? -> %s -----------------------------------------------------
def test_qmark_to_pct_s():
    assert translate_sql("SELECT * FROM users WHERE id=?") == \
        "SELECT * FROM users WHERE id=%s"


def test_multiple_placeholders():
    assert translate_sql("INSERT INTO t (a,b) VALUES (?,?)") == \
        "INSERT INTO t (a,b) VALUES (%s,%s)"


def test_qmark_inside_string_literal_preserved():
    # String-literal ichidagi ? tegmasligi kerak (haqiqiy savol belgisi)
    out = translate_sql("SELECT * FROM faq WHERE q='Ishladi?' AND id=?")
    assert "'Ishladi?'" in out
    assert out.endswith("id=%s")


# --- Literal % -> %% (psycopg talabi) ----------------------------------------
def test_percent_in_literal_doubled():
    assert translate_sql("INSERT INTO logs (msg) VALUES ('100% done')") == \
        "INSERT INTO logs (msg) VALUES ('100%% done')"


def test_like_pattern_percent_doubled():
    out = translate_sql("SELECT * FROM p WHERE name LIKE '%phone%' AND id=?")
    assert out == "SELECT * FROM p WHERE name LIKE '%%phone%%' AND id=%s"


# --- CURRENT_TIMESTAMP -> to_char(...) ---------------------------------------
def test_current_timestamp_translated():
    out = translate_sql("UPDATE users SET updated_at=CURRENT_TIMESTAMP WHERE id=?")
    assert "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')" in out
    assert out.endswith("WHERE id=%s")


def test_current_timestamp_inside_string_not_translated():
    # String literal ichidagi so'z tegmasin
    out = translate_sql("INSERT INTO t (note) VALUES ('CURRENT_TIMESTAMP')")
    assert "'CURRENT_TIMESTAMP'" in out
    assert "to_char" not in out


# --- INSERT OR IGNORE / REPLACE -> ON CONFLICT DO NOTHING --------------------
def test_insert_or_ignore():
    out = translate_sql("INSERT OR IGNORE INTO carts (u,p) VALUES (?,?)")
    assert out.startswith("INSERT INTO carts")
    assert out.rstrip().endswith("ON CONFLICT DO NOTHING")
    assert "OR IGNORE" not in out.upper()


def test_insert_or_replace():
    out = translate_sql("INSERT OR REPLACE INTO settings (k,v) VALUES (?,?)")
    assert out.startswith("INSERT INTO settings")
    assert out.rstrip().endswith("ON CONFLICT DO NOTHING")
    assert "OR REPLACE" not in out.upper()


def test_plain_insert_unchanged_no_on_conflict():
    out = translate_sql("INSERT INTO t (a) VALUES (?)")
    assert "ON CONFLICT" not in out


# --- datetime('now', ...) ----------------------------------------------------
def test_datetime_now_bare():
    out = translate_sql("SELECT datetime('now')")
    assert "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')" in out


def test_datetime_now_minus_days():
    out = translate_sql("SELECT * FROM o WHERE created_at >= datetime('now', '-7 days')")
    assert "now() AT TIME ZONE 'UTC' - interval '7 days'" in out


def test_datetime_now_plus_hours():
    out = translate_sql("SELECT datetime('now', '+3 hours')")
    assert "+ interval '3 hours'" in out


# --- strftime -> EXTRACT -----------------------------------------------------
def test_strftime_hour():
    out = translate_sql("SELECT strftime('%H', created_at) FROM o")
    assert "EXTRACT(HOUR FROM (created_at)::timestamp)" in out
    # literal % strftime ichida qolmasligi kerak (aks holda %% ga aylanadi)
    assert "%" not in out


def test_strftime_dow():
    out = translate_sql("SELECT strftime('%w', created_at) FROM o")
    assert "EXTRACT(DOW FROM (created_at)::timestamp)" in out


# --- DDL tip almashtirishlari ------------------------------------------------
def test_ddl_type_substitutions():
    out = translate_sql(
        "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, "
        "price REAL, ok BOOLEAN, ts TIMESTAMP, qty INTEGER)"
    )
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "DOUBLE PRECISION" in out
    assert "SMALLINT" in out
    assert "ts TEXT" in out
    assert "qty BIGINT" in out
    assert "AUTOINCREMENT" not in out
    assert "INTEGER" not in out


def test_ddl_substitutions_only_for_ddl_not_select():
    # SELECT'da INTEGER so'zi (masalan CAST) DDL sub'ga tushmasligi kerak
    out = translate_sql("SELECT CAST(x AS INTEGER) FROM t")
    assert "INTEGER" in out  # SELECT'da o'zgarmaydi


# --- PRAGMA shim darajasida no-op bo'ladi (execute'da), tarjima esa tegmaydi --
def test_pragma_passthrough_is_noop_in_cursor():
    # translate_sql PRAGMA'ga tegmaydi; no-op execute'da hal qilinadi.
    # Bu yerda faqat regex borligini tasdiqlaymiz.
    import re
    assert re.match(r"^\s*PRAGMA\b", "PRAGMA journal_mode=WAL", re.I)


# --- _split_literals to'g'ri ajratadi ----------------------------------------
def test_split_literals_handles_escaped_quote():
    parts = db_backend._split_literals("SELECT 'a''b' AS x WHERE id=?")
    # 'a''b' bitta string-literal bo'lib chiqishi kerak
    string_parts = [t for is_str, t in parts if is_str]
    assert "'a''b'" in string_parts
